### ISSUE TITLE
implement branch provider

### ISSUE THREAD

**Issue by ugurdonmez** [ugurdonmez/kinder-mobile#2]
implement methods under provider/branch

**getUserBranches**: returns ids of branches
read from user_branches data

**getBranch** return branch model
read from branches data

**addBranch** 
add to branches data

**updateBranch**

**Comment by ugurdonmez** [comment]
**addBranch**
burda once branches datasina eklenecek. ekleyince firebase unique bir id atayacak. o id de user-branches data sinda user id nin altindaki json arrayina eklenecek. user id yi authService de user mailinin @ dan onceki kismi olarak kullaniyoruz. once bu method u yaparsan test etmemiz kolay olur. elle data ekleyemedim firebase a.

**Comment by borakrc** [comment]
addBranch'i pushladim hocam.

branches ile user-branches baglantisini dedigin gibi yaptiktan sonra tekrar pushlayacagim. sonra da digerlerine bakacagim.

pushlarken merge conflict yedik bi de, resolve ettim ama sen de bir bak istersen.

**Comment by borakrc** [comment]
`let mockBranch: BranchModel = {}` seklinde mock branch yaratamiyorum, cunku BranchModel'in icinde id var ve benim yaratirken id de vermem gerekiyor. Ama id'yi BranchModel yaratip push'ladiktan sonra bize Firebase veriyor. id vermeden yaratmak icin de BranchModel'i interface yerine class yapmam gerekiyordu. Oyle yaptim.

**Comment by borakrc** [comment]
hocam hepsini tamamladim. updateBranch fonksiyonu da BranchModel aliyor parametre olarak. id'ye bakiyor ve ustune yaziyor. icinde class'lari [c1, c2, c3] olan bi branch'i da [c1, c3] seklinde update ediyor, c2'yi siliyor yani c2'siz update atarsak. onu da test ettim.

yalniz getUserBranches fonksiyonu biraz yavas calisiyor, ona sen de bir bakabilir misin?
