### ISSUE TITLE
Invitation for Managers

### ISSUE THREAD

**Issue by borakrc** [ugurdonmez/kinder-mobile#24]
Bunu soyle yapacagim:

**1. Super-Adminler, bir e-posta adresini branch admin olarak invite eder.**
Bunun icin bir 'Invite People' gibi bir ekran olusturacagim, invite ederken (super-admin haric) herkes kendinden alt seviyede bir user role ile invite edebilecek.

- Yani Super-Adminler her rol seviyesinden user inv edebilecek,
- Branch-Adminler, School-Admin, Teacher (yani Class-Admin), Parent ve Student inv edebilecek.
- School-Adminler, Teacher, Parent ve Student inv edebilecek
- Teacher'lar, Parent ve Student davet edecek.

Ama simdi oncelikli olarak sadece super-adminin branch-admin davet edebilmesini yapmam lazim benim.

**2. Davet edilen e-posta adresini /invited-users/branch-admins gibi bir collectiona pushlariz. (boyle bi collection kullanmamiz sart degil aslinda ama ilk asamada daha temiz olur) Bir de sign up olmasi icin e-posta gondeririz.**

**3. Register olan hesaplardan biri bu e-posta adresine sahipse o hesabi register ettikten sonra user role'unu 'Branch Admin' yapariz.** Register olduktan sonra da 'Create Branch' ekranina yonlendiririz. Create branch ekranindaki 'manager mail' fieldini tekrar doldutmayacagiz.

not: user rolu auth datasinin icinde belirtmemize izin vermiyor angularfire. bu yuzden yeni collectionlar yaratarak handle etmemiz gerekiyor bunlari.

**Comment by borakrc** [comment]
Davet edilen user'a mail atmak icin angularfire2 yerine firebase SDK'sini kullanmamiz onerilmis.

https://github.com/angular/angularfire2/issues/399

Ama "Sizin adiniza bir hesap olusturuldu, hadi sifreni belirle" seklinde ozellestirilemiyor buradan attigimiz e-postalar. Su anda sadece email verification, password reset ve email change yapilabiliyormus. Yeni e-mail template'i eklenmiyor gorunuyor.

Kullaniciyi sifresiz olarak kaydedip "kaydoldun, hadi sifreni belirle" gibi bir e-posta da yollamak icin firebase disinda bir cozum bulmamiz gerekiyor. fire-mail paketine SMTP credentials verdigimizde e-posta gonderebiliyoruz. (https://www.npmjs.com/package/fire-mail) Bu yolu izleyecegim.

**Comment by borakrc** [comment]
nodemailer paketini import ederken hata aliyorum. javascript olani import etmeyi de denedim. path'i relative verdim, tsconfig.json'da compilerOptions.types ve compilerOptions.typeRoots belirtmeyi onermisler, onu da denedim. npm update ettim, typescript versiyonunu en az 2.1.1 yapmayi onermisler onu yukselttim. global npm paketlerimi de sildim, sonra node_modules folder'ini silip bastan npm install yaptim. muhtemelen ufak bi noktayi gozden kaciriyorum. sen deneyebilir misin hocam? @ugurdonmez

**Comment by borakrc** [comment]
calismayan kod yeni actigim branchta

**Comment by borakrc** [comment]
import etmeye calistigim dosyanin basina asagidakini yazmayi da denedim

`/// <reference path="../../node_modules/@types/nodemailer/index.d.ts" />`

**Comment by ugurdonmez** [comment]
angular mail olayina bakmistim ben de. cok isimize yarar gibi durmuyordu ama baska turlu de nasil cozembiliriz dusunmemistim. bakmamiz lazim buna da.

**Comment by borakrc** [comment]
Aslinda smtp ustunden mail atabildigimiz modullerden birini basariyla import etsem halledebilicem ben.

Nodemailer'i ve @types/nodemailer'i package.json'a ekledim, birini benim icin import edebilir misin?

**Comment by ugurdonmez** [comment]
su asamada ona girmeyelim bora. hizlica ilerleyelim. kullanicilara mail sifreyi biz verecek sekilde yapalim. daha sonra sukru abilerin yonlendirmesiyle hareket ederiz.

**Comment by borakrc** [comment]
tamam hocam e-posta gönderme kısmını atlayarak yapacağım bunu.

**Comment by borakrc** [comment]
e-posta haric yaptim bunu
