### ISSUE TITLE
implement class provider

### ISSUE THREAD

**Issue by ugurdonmez** [ugurdonmez/kinder-mobile#5]
branch le ayni methodlar olacak. 

branch_class ile class tablolari olusacak. diger yaptiginin aynisi nerdeyse

**Comment by borakrc** [comment]
pushladim hocam. provider yazdim, test etmek icin school-admin-add-update-class page'ine bir buton ekleyip onla provider fonksiyonlarini cagirdim.

aynisini teacher, student ve parent icin de yapayim mi?

**Comment by borakrc** [comment]
hocam soyle bir sikinti var,

Model'larin icinde id attribute'i oldugu icin update yaptigimizda model'daki id'yi de attribute olarak atiyor Firebase'e. Daha aciklayici olmasi icin ss upload ediyorum.

Bu konuda bir sey yapalim mi?

![image](https://cloud.githubusercontent.com/assets/3453282/21957557/70cd78f8-daa1-11e6-8c1f-481df5d1ad75.png)
