### ISSUE TITLE
merge all logout method in service

### ISSUE THREAD

**Issue by ugurdonmez** [ugurdonmez/kinder-mobile#60]
write a header directive

**Comment by borakrc** [comment]
i take this

**Comment by borakrc** [comment]
hocam directive ile child element eklerken renderer.createElement() kullanmak gerekiyor. ama o da child elementlerin sonuna degil basina ekliyor elementi. basliktan once koyuyor logoyu yani. o yuzden ya basliktaki texti de bu directive ile ekleyecegiz, ya da bunu component yapip <logout-button></logout-button> diye ekleyecegiz html'e.

**Comment by ugurdonmez** [comment]
go with component. it is called directive in angular 1.
